"""empty message

Revision ID: 8ba65a77e39f
Revises: 0e63bcabf8e6
Create Date: 2022-03-16 13:52:57.222799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba65a77e39f'
down_revision = '0e63bcabf8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advertisement_model_date_key', 'advertisement_model', type_='unique')
    op.drop_constraint('advertisement_model_owner_key', 'advertisement_model', type_='unique')
    op.create_unique_constraint(None, 'advertisement_model', ['text'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement_model', type_='unique')
    op.create_unique_constraint('advertisement_model_owner_key', 'advertisement_model', ['owner'])
    op.create_unique_constraint('advertisement_model_date_key', 'advertisement_model', ['date'])
    # ### end Alembic commands ###
